/*
Proyecto: Pasarela / ERWIN -> PASARELA_ARTEZ
Clase origen: ErwinPasarelaArtezTransformer
Uso: ajustar variables DECLARE superiores y ejecutar en SSMS.
Fecha generación: 2026-05-06
*/

/* Método: DeleteByProcedimiento
   Ejecutar en BD destino: PASARELA_ARTEZ / PASARELA.
*/

-- USE PASARELA_ARTEZ;
-- GO

DECLARE @PROCEDIMIENTO nvarchar(255) = N'TA999900';

BEGIN TRAN;

DELETE FROM dbo.PARAM_ACC      WHERE PROCEDIMIENTO = @PROCEDIMIENTO;
DELETE FROM dbo.CONECTOR_ACC   WHERE PROCEDIMIENTO = @PROCEDIMIENTO;
DELETE FROM dbo.ACCIONES_DI    WHERE PROCEDIMIENTO = @PROCEDIMIENTO;
DELETE FROM dbo.PROPIEDADES_DI WHERE PROCEDIMIENTO = @PROCEDIMIENTO;
DELETE FROM dbo.CONECTORES_DI  WHERE PROCEDIMIENTO = @PROCEDIMIENTO;
DELETE FROM dbo.DIAGRAMA       WHERE PROCEDIMIENTO = @PROCEDIMIENTO;

SELECT 'PARAM_ACC' AS TABLA, COUNT(*) AS RESTANTES FROM dbo.PARAM_ACC WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'CONECTOR_ACC', COUNT(*) FROM dbo.CONECTOR_ACC WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'ACCIONES_DI', COUNT(*) FROM dbo.ACCIONES_DI WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'PROPIEDADES_DI', COUNT(*) FROM dbo.PROPIEDADES_DI WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'CONECTORES_DI', COUNT(*) FROM dbo.CONECTORES_DI WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'DIAGRAMA', COUNT(*) FROM dbo.DIAGRAMA WHERE PROCEDIMIENTO = @PROCEDIMIENTO;

-- Si está bien:
-- COMMIT;

-- Mientras pruebas:
ROLLBACK;
