/*
Proyecto: Pasarela / ERWIN -> PASARELA_ARTEZ
Clase origen: ErwinPasarelaArtezTransformer
Uso: ajustar variables DECLARE superiores y ejecutar en SSMS.
Fecha generación: 2026-05-06
*/

/* Método: InsertDiagrama
   Ejecutar en BD destino PASARELA_ARTEZ / PASARELA.
   Plantilla para insertar UNA fila.
*/

-- USE PASARELA_ARTEZ;
-- GO

DECLARE @PROCEDIMIENTO nvarchar(255) = N'TA999900';
DECLARE @ORDEN_N1 int = 1, @ORDEN_N2 int = 0, @ORDEN_N3 int = 0, @ORDEN_N4 int = 0, @ORDEN_N5 int = 0;
DECLARE @ID_DIAGRAMA int = 0, @ID_PADRE int = 0, @NUM_SEQ int = 0, @DI_ID int = 3750;
DECLARE @CAT_DIAGRAMA nvarchar(50) = N'P';
DECLARE @NOMBRE nvarchar(500) = N'PON_NOMBRE';
DECLARE @USERDEFINED varchar(max) = NULL;
DECLARE @NIVEL int = 1;
DECLARE @ARBOL nvarchar(1024) = N'000001';
DECLARE @PLAZOTIPO1 nvarchar(50) = NULL, @PLAZOTIPO2 nvarchar(50) = NULL, @NIV_TRAMIT nvarchar(50) = NULL;
DECLARE @BLOQUEO_EXP nvarchar(50) = NULL, @UNION_RAMAS nvarchar(50) = NULL, @TRAMIT_SIMUL nvarchar(50) = NULL;
DECLARE @TRAM_OCULTO nvarchar(50) = NULL, @IND_VALORVAR nvarchar(50) = NULL, @VUELTA_ATRAS nvarchar(50) = NULL;
DECLARE @NOMBRE_TRAM nvarchar(500) = @NOMBRE;

INSERT INTO dbo.DIAGRAMA
(
    PROCEDIMIENTO, ORDEN_N1, ORDEN_N2, ORDEN_N3, ORDEN_N4, ORDEN_N5,
    ID_DIAGRAMA, ID_PADRE, NUM_SEQ, DI_ID,
    CAT_DIAGRAMA, NOMBRE, USERDEFINED, NIVEL, ARBOL,
    PLAZOTIPO1, PLAZOTIPO2, NIV_TRAMIT, BLOQUEO_EXP, UNION_RAMAS,
    TRAMIT_SIMUL, TRAM_OCULTO, IND_VALORVAR, VUELTA_ATRAS, NOMBRE_TRAM
)
VALUES
(
    @PROCEDIMIENTO, @ORDEN_N1, @ORDEN_N2, @ORDEN_N3, @ORDEN_N4, @ORDEN_N5,
    @ID_DIAGRAMA, @ID_PADRE, @NUM_SEQ, @DI_ID,
    @CAT_DIAGRAMA, @NOMBRE, CONVERT(varchar(max), @USERDEFINED), @NIVEL, @ARBOL,
    @PLAZOTIPO1, @PLAZOTIPO2, @NIV_TRAMIT, @BLOQUEO_EXP, @UNION_RAMAS,
    @TRAMIT_SIMUL, @TRAM_OCULTO, @IND_VALORVAR, @VUELTA_ATRAS, @NOMBRE_TRAM
);
