/*
Proyecto: Pasarela / ERWIN -> PASARELA_ARTEZ
Clase origen: ErwinPasarelaArtezTransformer
Uso: ajustar variables DECLARE superiores y ejecutar en SSMS.
Fecha generación: 2026-05-06
*/

/* Verificación posterior de carga en PASARELA_ARTEZ / PASARELA. */

-- USE PASARELA_ARTEZ;
-- GO

DECLARE @PROCEDIMIENTO nvarchar(255) = N'TA999900';

SELECT 'DIAGRAMA' AS TABLA, COUNT(*) AS FILAS FROM dbo.DIAGRAMA WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'CONECTORES_DI', COUNT(*) FROM dbo.CONECTORES_DI WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'PROPIEDADES_DI', COUNT(*) FROM dbo.PROPIEDADES_DI WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'ACCIONES_DI', COUNT(*) FROM dbo.ACCIONES_DI WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'CONECTOR_ACC', COUNT(*) FROM dbo.CONECTOR_ACC WHERE PROCEDIMIENTO = @PROCEDIMIENTO
UNION ALL SELECT 'PARAM_ACC', COUNT(*) FROM dbo.PARAM_ACC WHERE PROCEDIMIENTO = @PROCEDIMIENTO;

SELECT TOP (100) * FROM dbo.DIAGRAMA WHERE PROCEDIMIENTO = @PROCEDIMIENTO ORDER BY ORDEN_N1, ORDEN_N2, ORDEN_N3, ORDEN_N4, ORDEN_N5;
SELECT TOP (100) * FROM dbo.CONECTORES_DI WHERE PROCEDIMIENTO = @PROCEDIMIENTO ORDER BY ORDEN_N1, ORDEN_N2, ORDEN_N3, ORDEN_N4, NUM;
SELECT TOP (100) * FROM dbo.ACCIONES_DI WHERE PROCEDIMIENTO = @PROCEDIMIENTO ORDER BY ORDEN_N1, ORDEN_ACC;
