USE erwin_evolve;
GO

DECLARE @MODEL_NAME NVARCHAR(255) = N'ARTEZELI';

SELECT
    D.DI_ID,
    D.DI_NAME,
    D.DI_TYPE,
    D.ANO_ID,
    D.ANO_TABNR
FROM dbo.DIAGRAM AS D
WHERE D.MODEL_NAME = @MODEL_NAME
ORDER BY D.DI_NAME;