/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [MODEL_NAME]
      ,[DI_ID]
      ,[ANO_ID]
      ,[ANO_TABNR]
      ,[DI_UNUSED_RULES_0]
      ,[DI_UNUSED_RULES_1]
      ,[DI_UNUSED_RULES_10]
      ,[DI_UNUSED_RULES_11]
      ,[DI_UNUSED_RULES_12]
      ,[DI_UNUSED_RULES_13]
      ,[DI_ROUNDCORNERS]
      ,[DI_LEVEL]
      ,[DI_UNUSED_RULES_2]
      ,[DI_UNUSED_RULES_3]
      ,[DI_UNUSED_RULES_4]
      ,[DI_UNUSED_RULES_5]
      ,[DI_UNUSED_RULES_6]
      ,[DI_UNUSED_RULES_7]
      ,[DI_UNUSED_RULES_8]
      ,[DI_UNUSED_RULES_9]
      ,[DI_DATE_VAL]
      ,[DI_DESCRIPTION]
      ,[DI_DIAGRAMMER]
      ,[DI_EXPORT_FLAG]
      ,[DI_GRID_SNAP]
      ,[DI_LANDSCAPE]
      ,[DI_NAME]
      ,[DI_ORIGIN_X]
      ,[DI_ORIGIN_Y]
      ,[DI_CONTEXTDIAGRAM]
      ,[DI_UNUSED_FLAGS_1]
      ,[DI_UNUSED_FLAGS_10]
      ,[DI_UNUSED_FLAGS_11]
      ,[DI_UNUSED_FLAGS_12]
      ,[DI_UNUSED_FLAGS_13]
      ,[DI_UNUSED_FLAGS_14]
      ,[DI_UNUSED_FLAGS_15]
      ,[DI_UNUSED_FLAGS_2]
      ,[DI_UNUSED_FLAGS_3]
      ,[DI_UNUSED_FLAGS_4]
      ,[DI_UNUSED_FLAGS_5]
      ,[DI_LAYOUTOPTION]
      ,[DI_UNUSED_FLAGS_7]
      ,[DI_UNUSED_FLAGS_8]
      ,[DI_UNUSED_FLAGS_9]
      ,[DI_PAPER_SIZE]
      ,[DI_PRINT_MAP]
      ,[DI_PRINT_SCALE]
      ,[DI_SCALE]
      ,[DI_SYMBOLS]
      ,[DI_TEMPLATE]
      ,[DI_TITLE]
      ,[DI_TOTAL_OBJECTS]
      ,[DI_TYPE]
      ,[DI_UUID]
      ,[DI_VALIDATED]
      ,[DI_WHEN_CREATED]
      ,[DI_WHEN_UPDATED]
      ,[DI_WHO_CREATED]
      ,[DI_WHO_OWNS]
      ,[DI_WHO_UPDATED]
      ,[ST_ID]
      ,[ST_ID_DIDEF]
      ,[USERDEFINED]
      ,[US_ID]
  FROM [erwin_evolve].[dbo].[DIAGRAM]
  WHERE DI_NAME LIKE 'P00010%'
  AND MODEL_NAME = 'BIDERAT1'



  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT [DI_ID]
  FROM [erwin_evolve].[dbo].[DIAGRAM]
  WHERE DI_NAME LIKE 'P00010%'
  AND MODEL_NAME = 'BIDERAT1'