/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [PROCEDIMIENTO]
      ,[ORDEN_N1]
      ,[ORDEN_N2]
      ,[ORDEN_N3]
      ,[ORDEN_N4]
      ,[ORDEN_N5]
      ,[ID_DIAG_N1]
      ,[ID_DIAG_N2]
      ,[ID_DIAG_N3]
      ,[ID_DIAG_N4]
      ,[ID_DIAG_N5]
      ,[ID_DIAGRAMA]
      ,[CAT_DIAGRAMA]
      ,[ID_PADRE]
      ,[NUM_DIAGRAMA]
      ,[EXPLOTA_ACC]
      ,[NUM_SEQ]
      ,[INDPARA]
      ,[INDJUMP]
      ,[INDCANCEL]
      ,[NOMBRE]
      ,[SALIDAS]
      ,[INDCOMUN]
      ,[DI_ID]
      ,[NIVEL]
      ,[ARBOL]
      ,[USERDEFINED]
      ,[PLAZOTIPO1]
      ,[PLAZOTIPO2]
      ,[NIV_TRAMIT]
      ,[BLOQUEO_EXP]
      ,[UNION_RAMAS]
      ,[TRAMIT_SIMUL]
      ,[TRAM_OCULTO]
      ,[IND_VALORVAR]
      ,[VUELTA_ATRAS]
      ,[NOMBRE_TRAM]
      ,[CODFASE]
      ,[CODSFASE]
      ,[DATFASUB]
  FROM [PASARELA].[dbo].[DIAGRAMA]

  WHERE PROCEDIMIENTO like '%P000%'