flowchart TD
    msCorregirTramites["msCorregirTramites()"] --> Mostrar_Error["Mostrar_Error()"]
    msLec_Diagram_Proc["msLec_Diagram_Proc()"] --> Mostrar_Error["Mostrar_Error()"]
    msLec_Diagram_Proc["msLec_Diagram_Proc()"] --> mfFaseSubfase["mfFaseSubfase()"]
    msLec_Diagram_Proc["msLec_Diagram_Proc()"] --> msLec_Conectores_DI["msLec_Conectores_DI()"]
    msLec_Diagram_Proc["msLec_Diagram_Proc()"] --> msLec_Diagram_Proc["msLec_Diagram_Proc()"]
    msLec_Diagram_Proc["msLec_Diagram_Proc()"] --> msProceso["msProceso()"]
    msLec_Conectores_DI["msLec_Conectores_DI()"] --> Mostrar_Error["Mostrar_Error()"]
    msLec_Conectores_DI["msLec_Conectores_DI()"] --> mfBuscaXML["mfBuscaXML()"]
    msLec_Conectores_DI["msLec_Conectores_DI()"] --> msProceso["msProceso()"]
    msMismoEnlaceSinDefinir["msMismoEnlaceSinDefinir()"] --> mfBuscaXML["mfBuscaXML()"]
    msMismoEnlaceSinDefinir["msMismoEnlaceSinDefinir()"] --> msMismoEnlaceSinDefinir["msMismoEnlaceSinDefinir()"]
    msProceso["msProceso()"]
    msPropiedades_Proc["msPropiedades_Proc()"] --> Mostrar_Error["Mostrar_Error()"]
    msPropiedades_Proc["msPropiedades_Proc()"] --> mfBuscaXML["mfBuscaXML()"]
    msPropiedades_Proc["msPropiedades_Proc()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msPropiedades_Proc["msPropiedades_Proc()"] --> msProceso["msProceso()"]
    msPruebaTDAUTOMATICA["msPruebaTDAUTOMATICA()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msVariables_Alta["msVariables_Alta()"] --> Mostrar_Error["Mostrar_Error()"]
    msVariables_Alta["msVariables_Alta()"] --> mfInsertaVariables["mfInsertaVariables()"]
    msVariables_Alta["msVariables_Alta()"] --> msProceso["msProceso()"]
    msUd_Tramitacion["msUd_Tramitacion()"] --> Mostrar_Error["Mostrar_Error()"]
    msUd_Tramitacion["msUd_Tramitacion()"] --> mfBuscaXML["mfBuscaXML()"]
    msUd_Tramitacion["msUd_Tramitacion()"] --> mfUnidTra["mfUnidTra()"]
    msUd_Tramitacion["msUd_Tramitacion()"] --> msProceso["msProceso()"]
    msLecTramRamif["msLecTramRamif()"] --> Mostrar_Error["Mostrar_Error()"]
    msLecTramRamif["msLecTramRamif()"] --> mfBuscaXML["mfBuscaXML()"]
    msLecTramRamif["msLecTramRamif()"] --> mfTratamientoCM10["mfTratamientoCM10()"]
    msLecTramRamif["msLecTramRamif()"] --> mfUnidTra["mfUnidTra()"]
    msLecTramRamif["msLecTramRamif()"] --> mfUnidTraComunicacion["mfUnidTraComunicacion()"]
    msLecTramRamif["msLecTramRamif()"] --> msActVar["msActVar()"]
    msLecTramRamif["msLecTramRamif()"] --> msAcusRecTele["msAcusRecTele()"]
    msLecTramRamif["msLecTramRamif()"] --> msBuscarvbFirma["msBuscarvbFirma()"]
    msLecTramRamif["msLecTramRamif()"] --> msFirma["msFirma()"]
    msLecTramRamif["msLecTramRamif()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msLecTramRamif["msLecTramRamif()"] --> msObtenerResponsableFirmaExterno["msObtenerResponsableFirmaExterno()"]
    msLecTramRamif["msLecTramRamif()"] --> msPlazT1["msPlazT1()"]
    msLecTramRamif["msLecTramRamif()"] --> msPlazT2["msPlazT2()"]
    msLecTramRamif["msLecTramRamif()"] --> msProceso["msProceso()"]
    msLecTramRamif["msLecTramRamif()"] --> msTablasInfra["msTablasInfra()"]
    msLecTramRamif["msLecTramRamif()"] --> msUnRamPa["msUnRamPa()"]
    msLecTramRamif["msLecTramRamif()"] --> msUnidTraRami["msUnidTraRami()"]
    msLecTramRamif["msLecTramRamif()"] --> msVBResp1["msVBResp1()"]
    msLecTramRamif["msLecTramRamif()"] --> msVBResp2["msVBResp2()"]
    cmdCancelar_Click["cmdCancelar_Click()"] --> msPasarProcedimientos["msPasarProcedimientos()"]
    CmdCancelarActual_Click["CmdCancelarActual_Click()"] --> msPasarProcedimientos["msPasarProcedimientos()"]
    cmdForzar_Click["cmdForzar_Click()"]
    frmProceso_Activated["frmProceso_Activated()"]
    msLec_Conectores_ACC["msLec_Conectores_ACC()"] --> Mostrar_Error["Mostrar_Error()"]
    msLec_Conectores_ACC["msLec_Conectores_ACC()"] --> mfBuscaXML["mfBuscaXML()"]
    msLec_Conectores_ACC["msLec_Conectores_ACC()"] --> msProceso["msProceso()"]
    msTablasInfra["msTablasInfra()"] --> Mostrar_Error["Mostrar_Error()"]
    msTablasInfra["msTablasInfra()"] --> mfBuscaXML["mfBuscaXML()"]
    msTablasInfra["msTablasInfra()"] --> mfInsertaVariablesNOMBRE["mfInsertaVariablesNOMBRE()"]
    msUnidTraRami["msUnidTraRami()"]
    mfUnidTra["mfUnidTra()"] --> Mostrar_Error["Mostrar_Error()"]
    mfUnidTra["mfUnidTra()"] --> mfUnidTra["mfUnidTra()"]
    mfFaseSubfase["mfFaseSubfase()"] --> Mostrar_Error["Mostrar_Error()"]
    mfFaseSubfase["mfFaseSubfase()"] --> mfFaseSubfase["mfFaseSubfase()"]
    msUnRamPa["msUnRamPa()"] --> Mostrar_Error["Mostrar_Error()"]
    msPlazT1["msPlazT1()"] --> Mostrar_Error["Mostrar_Error()"]
    msPlazT1["msPlazT1()"] --> mfBuscaXML["mfBuscaXML()"]
    msPlazT1["msPlazT1()"] --> mfInsertaVariables["mfInsertaVariables()"]
    msPlazT1["msPlazT1()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msLecAccTram["msLecAccTram()"] --> CrearAccion["CrearAccion()"]
    msLecAccTram["msLecAccTram()"] --> Mostrar_Error["Mostrar_Error()"]
    msLecAccTram["msLecAccTram()"] --> SolucionarINDTIPOA["SolucionarINDTIPOA()"]
    msLecAccTram["msLecAccTram()"] --> msProceso["msProceso()"]
    mfBuscaXML["mfBuscaXML()"] --> Mostrar_Error["Mostrar_Error()"]
    mfBuscaXML["mfBuscaXML()"] --> mfBuscaXML["mfBuscaXML()"]
    mfInsertaVariables["mfInsertaVariables()"] --> Mostrar_Error["Mostrar_Error()"]
    mfInsertaVariables["mfInsertaVariables()"] --> mfInsertaVariables["mfInsertaVariables()"]
    msInsertaParamAcc["msInsertaParamAcc()"] --> Mostrar_Error["Mostrar_Error()"]
    msInsertaParamAcc["msInsertaParamAcc()"] --> mfInsertaVariablesNOMBRE["mfInsertaVariablesNOMBRE()"]
    msInsertaParamAcc["msInsertaParamAcc()"] --> mfObtieneRuta["mfObtieneRuta()"]
    mslecParamAcc["mslecParamAcc()"] --> Mostrar_Error["Mostrar_Error()"]
    mslecParamAcc["mslecParamAcc()"] --> fArranque_Automatico["fArranque_Automatico()"]
    mslecParamAcc["mslecParamAcc()"] --> fComprobacion_DOC["fComprobacion_DOC()"]
    mslecParamAcc["mslecParamAcc()"] --> fEnv_Mens["fEnv_Mens()"]
    mslecParamAcc["mslecParamAcc()"] --> fEval_Ind_Requis["fEval_Ind_Requis()"]
    mslecParamAcc["mslecParamAcc()"] --> fImpres_Doc["fImpres_Doc()"]
    mslecParamAcc["mslecParamAcc()"] --> fInitVar["fInitVar()"]
    mslecParamAcc["mslecParamAcc()"] --> fIntroCampoOb["fIntroCampoOb()"]
    mslecParamAcc["mslecParamAcc()"] --> fIntroDatos["fIntroDatos()"]
    mslecParamAcc["mslecParamAcc()"] --> fPresen_Mens["fPresen_Mens()"]
    mslecParamAcc["mslecParamAcc()"] --> fSin_Implementacion["fSin_Implementacion()"]
    mslecParamAcc["mslecParamAcc()"] --> fTD_Aut["fTD_Aut()"]
    mslecParamAcc["mslecParamAcc()"] --> fTD_Usu["fTD_Usu()"]
    mslecParamAcc["mslecParamAcc()"] --> fTrat_Docum["fTrat_Docum()"]
    mslecParamAcc["mslecParamAcc()"] --> fTrat_Varios["fTrat_Varios()"]
    mslecParamAcc["mslecParamAcc()"] --> mfBuscaXML["mfBuscaXML()"]
    mslecParamAcc["mslecParamAcc()"] --> mfInsertaVariables["mfInsertaVariables()"]
    mslecParamAcc["mslecParamAcc()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    mslecParamAcc["mslecParamAcc()"] --> msProceso["msProceso()"]
    fArranque_Automatico["fArranque_Automatico()"] --> Mostrar_Error["Mostrar_Error()"]
    fArranque_Automatico["fArranque_Automatico()"] --> fArranque_Automatico["fArranque_Automatico()"]
    fArranque_Automatico["fArranque_Automatico()"] --> mfBuscaXML["mfBuscaXML()"]
    fArranque_Automatico["fArranque_Automatico()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fArranque_Automatico["fArranque_Automatico()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fTrat_Varios["fTrat_Varios()"] --> Mostrar_Error["Mostrar_Error()"]
    fTrat_Varios["fTrat_Varios()"] --> fTrat_Varios["fTrat_Varios()"]
    fTrat_Varios["fTrat_Varios()"] --> mfBuscaXML["mfBuscaXML()"]
    fTrat_Varios["fTrat_Varios()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fTrat_Varios["fTrat_Varios()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fEval_Ind_Requis["fEval_Ind_Requis()"] --> Mostrar_Error["Mostrar_Error()"]
    fEval_Ind_Requis["fEval_Ind_Requis()"] --> fEval_Ind_Requis["fEval_Ind_Requis()"]
    fEval_Ind_Requis["fEval_Ind_Requis()"] --> mfBuscaXML["mfBuscaXML()"]
    fEval_Ind_Requis["fEval_Ind_Requis()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fEval_Ind_Requis["fEval_Ind_Requis()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fImpres_Doc["fImpres_Doc()"] --> Mostrar_Error["Mostrar_Error()"]
    fImpres_Doc["fImpres_Doc()"] --> fImpres_Doc["fImpres_Doc()"]
    fImpres_Doc["fImpres_Doc()"] --> mfBuscaXML["mfBuscaXML()"]
    fImpres_Doc["fImpres_Doc()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fImpres_Doc["fImpres_Doc()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fIntroDatos["fIntroDatos()"] --> Mostrar_Error["Mostrar_Error()"]
    fIntroDatos["fIntroDatos()"] --> fIntroDatos["fIntroDatos()"]
    fIntroDatos["fIntroDatos()"] --> mfBuscaXML["mfBuscaXML()"]
    fIntroDatos["fIntroDatos()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fIntroDatos["fIntroDatos()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fPresen_Mens["fPresen_Mens()"] --> Mostrar_Error["Mostrar_Error()"]
    fPresen_Mens["fPresen_Mens()"] --> fPresen_Mens["fPresen_Mens()"]
    fPresen_Mens["fPresen_Mens()"] --> mfBuscaXML["mfBuscaXML()"]
    fPresen_Mens["fPresen_Mens()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fPresen_Mens["fPresen_Mens()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fTD_Aut["fTD_Aut()"] --> Mostrar_Error["Mostrar_Error()"]
    fTD_Aut["fTD_Aut()"] --> fTD_Aut["fTD_Aut()"]
    fTD_Aut["fTD_Aut()"] --> mfBuscaXML["mfBuscaXML()"]
    fTD_Aut["fTD_Aut()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fTD_Aut["fTD_Aut()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fTD_Aut["fTD_Aut()"] --> msPruebaTDAUTOMATICA["msPruebaTDAUTOMATICA()"]
    fTD_Usu["fTD_Usu()"] --> Mostrar_Error["Mostrar_Error()"]
    fTD_Usu["fTD_Usu()"] --> fTD_Usu["fTD_Usu()"]
    fTD_Usu["fTD_Usu()"] --> mfBuscaXML["mfBuscaXML()"]
    fTD_Usu["fTD_Usu()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fEnv_Mens["fEnv_Mens()"] --> Mostrar_Error["Mostrar_Error()"]
    fEnv_Mens["fEnv_Mens()"] --> fEnv_Mens["fEnv_Mens()"]
    fEnv_Mens["fEnv_Mens()"] --> mfBuscaXML["mfBuscaXML()"]
    fEnv_Mens["fEnv_Mens()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fEnv_Mens["fEnv_Mens()"] --> mfInsertaVariablesNOMBRE["mfInsertaVariablesNOMBRE()"]
    fEnv_Mens["fEnv_Mens()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msBuscarCancel["msBuscarCancel()"] --> Mostrar_Error["Mostrar_Error()"]
    msBuscarCancel["msBuscarCancel()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msFirma["msFirma()"] --> Mostrar_Error["Mostrar_Error()"]
    msFirma["msFirma()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msBuscarvbFirma["msBuscarvbFirma()"] --> Mostrar_Error["Mostrar_Error()"]
    msBuscarvbFirma["msBuscarvbFirma()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msObtenerResponsableFirmaExterno["msObtenerResponsableFirmaExterno()"] --> Mostrar_Error["Mostrar_Error()"]
    msObtenerResponsableFirmaExterno["msObtenerResponsableFirmaExterno()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msVBResp1["msVBResp1()"] --> Mostrar_Error["Mostrar_Error()"]
    msVBResp1["msVBResp1()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msVBResp2["msVBResp2()"] --> Mostrar_Error["Mostrar_Error()"]
    msVBResp2["msVBResp2()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msRepaso["msRepaso()"] --> Mostrar_Error["Mostrar_Error()"]
    msRepaso["msRepaso()"] --> msBuscarCancel["msBuscarCancel()"]
    msRepaso["msRepaso()"] --> msConectoresOpcionales["msConectoresOpcionales()"]
    msRepaso["msRepaso()"] --> msEnlaces_sin_Definir["msEnlaces_sin_Definir()"]
    msRepaso["msRepaso()"] --> msFly["msFly()"]
    msRepaso["msRepaso()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msRepaso["msRepaso()"] --> msJumpsNoDetectados["msJumpsNoDetectados()"]
    msRepaso["msRepaso()"] --> msMetoCaducar["msMetoCaducar()"]
    msRepaso["msRepaso()"] --> msProceso["msProceso()"]
    msRepaso["msRepaso()"] --> msResolPlazTip2["msResolPlazTip2()"]
    msRepaso["msRepaso()"] --> msResolPlazo1["msResolPlazo1()"]
    msRepaso["msRepaso()"] --> msResolVariables["msResolVariables()"]
    msRepaso["msRepaso()"] --> msSolucionCaducar["msSolucionCaducar()"]
    msRepaso["msRepaso()"] --> msSolucionJumps["msSolucionJumps()"]
    msRepaso["msRepaso()"] --> msSolucionRampa["msSolucionRampa()"]
    msRepaso["msRepaso()"] --> msSolucionWait["msSolucionWait()"]
    msPlazT2["msPlazT2()"] --> Mostrar_Error["Mostrar_Error()"]
    msPlazT2["msPlazT2()"] --> mfBuscaXML["mfBuscaXML()"]
    msPlazT2["msPlazT2()"] --> mfInsertaVariables["mfInsertaVariables()"]
    msPlazT2["msPlazT2()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msResolPlazTip2["msResolPlazTip2()"] --> Mostrar_Error["Mostrar_Error()"]
    msResolPlazTip2["msResolPlazTip2()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msActVar["msActVar()"] --> Mostrar_Error["Mostrar_Error()"]
    msConectoresOpcionales["msConectoresOpcionales()"] --> Mostrar_Error["Mostrar_Error()"]
    msConectoresOpcionales["msConectoresOpcionales()"] --> mfBuscaXML["mfBuscaXML()"]
    msConectoresOpcionales["msConectoresOpcionales()"] --> mfInsertaVariables["mfInsertaVariables()"]
    msConectoresOpcionales["msConectoresOpcionales()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msActualizarSalidas["msActualizarSalidas()"] --> Mostrar_Error["Mostrar_Error()"]
    msCrearFlujo["msCrearFlujo()"] --> Mostrar_Error["Mostrar_Error()"]
    msCrearFlujo["msCrearFlujo()"] --> msProceso["msProceso()"]
    msOptimizarFlujo["msOptimizarFlujo()"] --> msEliminarEDPyPRO["msEliminarEDPyPRO()"]
    msOptimizarFlujo["msOptimizarFlujo()"] --> msRemplazarTDA_por_IF["msRemplazarTDA_por_IF()"]
    msEliminarJUMP_SiguienteInstruccion["msEliminarJUMP_SiguienteInstruccion()"]
    msRemplazarTDA_por_IF["msRemplazarTDA_por_IF()"] --> Mostrar_Error["Mostrar_Error()"]
    msEliminarEDPyPRO["msEliminarEDPyPRO()"] --> Mostrar_Error["Mostrar_Error()"]
    msCrearTramites["msCrearTramites()"] --> Mostrar_Error["Mostrar_Error()"]
    msCrearTramites["msCrearTramites()"] --> msCorregirTramites["msCorregirTramites()"]
    msCrearTramites["msCrearTramites()"] --> msProceso["msProceso()"]
    msCargarInfraestructura["msCargarInfraestructura()"] --> Mostrar_Error["Mostrar_Error()"]
    msCargarInfraestructura["msCargarInfraestructura()"] --> msProceso["msProceso()"]
    msVariablesInfra["msVariablesInfra()"] --> msProceso["msProceso()"]
    msCargarFlujo["msCargarFlujo()"] --> msProcEnCola["msProcEnCola()"]
    msCargarFlujo["msCargarFlujo()"] --> msProceso["msProceso()"]
    fInitVar["fInitVar()"] --> Mostrar_Error["Mostrar_Error()"]
    fInitVar["fInitVar()"] --> fInitVar["fInitVar()"]
    fInitVar["fInitVar()"] --> mfBuscaXML["mfBuscaXML()"]
    fInitVar["fInitVar()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fInitVar["fInitVar()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fSin_Implementacion["fSin_Implementacion()"] --> Mostrar_Error["Mostrar_Error()"]
    fSin_Implementacion["fSin_Implementacion()"] --> fSin_Implementacion["fSin_Implementacion()"]
    fSin_Implementacion["fSin_Implementacion()"] --> mfBuscaXML["mfBuscaXML()"]
    fSin_Implementacion["fSin_Implementacion()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fSin_Implementacion["fSin_Implementacion()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fComprobacion_DOC["fComprobacion_DOC()"] --> Mostrar_Error["Mostrar_Error()"]
    fComprobacion_DOC["fComprobacion_DOC()"] --> fComprobacion_DOC["fComprobacion_DOC()"]
    fComprobacion_DOC["fComprobacion_DOC()"] --> mfBuscaXML["mfBuscaXML()"]
    fComprobacion_DOC["fComprobacion_DOC()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fComprobacion_DOC["fComprobacion_DOC()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msSolucionJumps["msSolucionJumps()"] --> Mostrar_Error["Mostrar_Error()"]
    msSolucionJumps["msSolucionJumps()"] --> mfComprobarFDP["mfComprobarFDP()"]
    msSolucionJumps["msSolucionJumps()"] --> mfConectoresValidos["mfConectoresValidos()"]
    msSolucionJumps["msSolucionJumps()"] --> msCalc["msCalc()"]
    msSolucionJumps["msSolucionJumps()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msSolucionJumps["msSolucionJumps()"] --> msNivelSuperior["msNivelSuperior()"]
    msCalc["msCalc()"] --> msCalc["msCalc()"]
    msSolucionWait["msSolucionWait()"] --> Mostrar_Error["Mostrar_Error()"]
    msSolucionWait["msSolucionWait()"] --> mfBuscaXML["mfBuscaXML()"]
    msSolucionWait["msSolucionWait()"] --> mfInsertaVariables["mfInsertaVariables()"]
    msSolucionWait["msSolucionWait()"] --> mfMeteOpcionalParaWait["mfMeteOpcionalParaWait()"]
    msSolucionWait["msSolucionWait()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msSolucionRampa["msSolucionRampa()"] --> Mostrar_Error["Mostrar_Error()"]
    msSolucionRampa["msSolucionRampa()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msFly["msFly()"] --> Mostrar_Error["Mostrar_Error()"]
    msProcEnCola["msProcEnCola()"] --> frmProceso_Activated["frmProceso_Activated()"]
    msValidaciones["msValidaciones()"] --> Mostrar_Error["Mostrar_Error()"]
    msValidaciones["msValidaciones()"] --> formatGTC["formatGTC()"]
    msValidaciones["msValidaciones()"] --> logTiempos["logTiempos()"]
    msValidaciones["msValidaciones()"] --> msProceso["msProceso()"]
    msSolucionCaducar["msSolucionCaducar()"] --> Mostrar_Error["Mostrar_Error()"]
    mfUnidTraComunicacion["mfUnidTraComunicacion()"] --> Mostrar_Error["Mostrar_Error()"]
    mfUnidTraComunicacion["mfUnidTraComunicacion()"] --> mfUnidTra["mfUnidTra()"]
    mfUnidTraComunicacion["mfUnidTraComunicacion()"] --> mfUnidTraComunicacion["mfUnidTraComunicacion()"]
    mfInsertaVariablesNOMBRE["mfInsertaVariablesNOMBRE()"] --> Mostrar_Error["Mostrar_Error()"]
    mfInsertaVariablesNOMBRE["mfInsertaVariablesNOMBRE()"] --> mfInsertaVariablesNOMBRE["mfInsertaVariablesNOMBRE()"]
    msResolPlazo1["msResolPlazo1()"] --> Mostrar_Error["Mostrar_Error()"]
    msResolVariables["msResolVariables()"] --> Mostrar_Error["Mostrar_Error()"]
    msResolVariables["msResolVariables()"] --> mfBuscaXML["mfBuscaXML()"]
    msResolVariables["msResolVariables()"] --> mfInsertaVariables["mfInsertaVariables()"]
    msResolVariables["msResolVariables()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msJumpsNoDetectados["msJumpsNoDetectados()"] --> Mostrar_Error["Mostrar_Error()"]
    msJumpsNoDetectados["msJumpsNoDetectados()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    fIntroCampoOb["fIntroCampoOb()"] --> Mostrar_Error["Mostrar_Error()"]
    fIntroCampoOb["fIntroCampoOb()"] --> fIntroCampoOb["fIntroCampoOb()"]
    fIntroCampoOb["fIntroCampoOb()"] --> mfBuscaXML["mfBuscaXML()"]
    fIntroCampoOb["fIntroCampoOb()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fIntroCampoOb["fIntroCampoOb()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    msAcusRecTele["msAcusRecTele()"] --> Mostrar_Error["Mostrar_Error()"]
    msAcusRecTele["msAcusRecTele()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    logTiempos["logTiempos()"]
    formatGTC["formatGTC()"] --> formatGTC["formatGTC()"]
    frmProceso_Load["frmProceso_Load()"] --> FormatoHoras["FormatoHoras()"]
    frmProceso_Load["frmProceso_Load()"] --> cerrarConexiones["cerrarConexiones()"]
    tmrProg_Tick["tmrProg_Tick()"] --> FormatoHoras["FormatoHoras()"]
    tmrProg_Tick["tmrProg_Tick()"] --> arrancarConexiones["arrancarConexiones()"]
    tmrProg_Tick["tmrProg_Tick()"] --> msPasarProcedimientos["msPasarProcedimientos()"]
    FormatoHoras["FormatoHoras()"] --> FormatoHoras["FormatoHoras()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> Mostrar_Error["Mostrar_Error()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msActualizarSalidas["msActualizarSalidas()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msAdaptarFlujosRamasUnion["msAdaptarFlujosRamasUnion()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msCargarFlujo["msCargarFlujo()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msCargarInfraestructura["msCargarInfraestructura()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msComprobarNombres["msComprobarNombres()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msCrearFlujo["msCrearFlujo()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msCrearTramites["msCrearTramites()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msEliminarJUMP_SiguienteInstruccion["msEliminarJUMP_SiguienteInstruccion()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msLecAccTram["msLecAccTram()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msLecTramRamif["msLecTramRamif()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msLec_Conectores_ACC["msLec_Conectores_ACC()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msLec_Diagram_Proc["msLec_Diagram_Proc()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msModificacionesTramites["msModificacionesTramites()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msOptimizarFlujo["msOptimizarFlujo()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msPropiedades_Proc["msPropiedades_Proc()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msRepaso["msRepaso()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msUd_Tramitacion["msUd_Tramitacion()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msValidaciones["msValidaciones()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msVariablesInfra["msVariablesInfra()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> msVariables_Alta["msVariables_Alta()"]
    msPasarProcedimientos["msPasarProcedimientos()"] --> mslecParamAcc["mslecParamAcc()"]
    fTrat_Docum["fTrat_Docum()"] --> Mostrar_Error["Mostrar_Error()"]
    fTrat_Docum["fTrat_Docum()"] --> fTrat_Docum["fTrat_Docum()"]
    fTrat_Docum["fTrat_Docum()"] --> mfBuscaXML["mfBuscaXML()"]
    fTrat_Docum["fTrat_Docum()"] --> mfInsertaVariables["mfInsertaVariables()"]
    fTrat_Docum["fTrat_Docum()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    Mostrar_Error["Mostrar_Error()"]
    cmdNotepad_Click["cmdNotepad_Click()"]
    mfConectoresValidos["mfConectoresValidos()"] --> mfConectoresValidos["mfConectoresValidos()"]
    arrancarConexiones["arrancarConexiones()"]
    cerrarConexiones["cerrarConexiones()"]
    CrearAccion["CrearAccion()"] --> CrearAccion["CrearAccion()"]
    CrearAccion["CrearAccion()"] --> mfBuscaXML["mfBuscaXML()"]
    SolucionarINDTIPOA["SolucionarINDTIPOA()"] --> mfBuscaXML["mfBuscaXML()"]
    msComprobarNombres["msComprobarNombres()"]
    mfObtieneRuta["mfObtieneRuta()"] --> mfObtieneRuta["mfObtieneRuta()"]
    msEnlaces_sin_Definir["msEnlaces_sin_Definir()"] --> msMismoEnlaceSinDefinir["msMismoEnlaceSinDefinir()"]
    msMetoCaducar["msMetoCaducar()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    mfComprobarFDP["mfComprobarFDP()"] --> mfComprobarFDP["mfComprobarFDP()"]
    mfMeteOpcionalParaWait["mfMeteOpcionalParaWait()"] --> mfBuscaXML["mfBuscaXML()"]
    mfMeteOpcionalParaWait["mfMeteOpcionalParaWait()"] --> mfInsertaVariables["mfInsertaVariables()"]
    mfMeteOpcionalParaWait["mfMeteOpcionalParaWait()"] --> msInsertaParamAcc["msInsertaParamAcc()"]
    mfTratamientoCM10["mfTratamientoCM10()"] --> mfTratamientoCM10["mfTratamientoCM10()"]
    msNivelSuperior["msNivelSuperior()"]
    mfBuscaTramiteTDUSuperior["mfBuscaTramiteTDUSuperior()"] --> mfBuscaTramiteTDUSuperior["mfBuscaTramiteTDUSuperior()"]
    mfBuscaTramiteTDUSuperior["mfBuscaTramiteTDUSuperior()"] --> mfBuscaXML["mfBuscaXML()"]
    msModificacionesTramites["msModificacionesTramites()"] --> msProceso["msProceso()"]
    msAdaptarFlujosRamasUnion["msAdaptarFlujosRamasUnion()"]